# Made by RandomHashTags
gui:
  title: "Island Upgrades"
  size: 9
  #
  added lore:
    - " "
    - "&e&lTier"
    - "{TIER}"
    - " "
    - "&e&lUpgrade Bonus"
    - "{UPGRADE_BONUS}"
    - " "
    - "&c&lCost"
    - "{COST}"
    - " "
    - "&aClick to purchase &nupgrade&r&a!"
#