# Made by RandomHashTags
messages:
  mobs slain:
    - "&e&l(!)7r &e{TYPE} slain: &7{PROGRESS} / {COMPLETION} (&e{COMPLETION%}&7)"
#
skill:
  item: "diamond_sword"
  name: "&a&lSlayer"
  type: "Slayer"
#
gui:
  title: "/is slayer"
  size: 18
  background:
    item: "black_stained_glass_pane"
    name: " "
  settings:
    format:
      - " "
      - "{PROGRESS}"
      - "{RESPAWN_RATE}"
      - " "
      - "{STATUS}"
    progression:
      - "&f{COMPLETION%}% &7Unlocked"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Slain"
      - " "
    unlocked:
      name: "&a&l{NAME}"
      lore:
        - "&a&lUNLOCKED"
    locked:
      name: "&c&l{NAME}"
      lore:
        - "&c&lLOCKED"
    respawn rate:
      - "&f{RESPAWN%}% &7Respawn Rate"
      - "&7{PROGRESS} {TYPE} Slain"
  #
#
default skill: RABBIT
#