# Made by RandomHashTags
skill:
  item: "diamond_pickaxe"
  name: "&a&lMining"
  type: "Mining"
#
gui:
  title: "/is mining"
  size: 18
  background:
    item: "black_stained_glass_pane"
    name: " "
  #
  settings:
    format:
      - " "
      - "&f{COMPLETION%}% &7Complete"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
      - "{OR}"
      - " "
      - "{RESPAWN_RATE}"
    or format:
      - " &7&l&nOR"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
    respawn rate:
      - "&f{RESPAWN%}% &7Respawn Rate"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
    #
    locked:
      name: "&c&l{NAME}"
      added lore:
        - "&c&lLOCKED"
    unlocked:
      name: "&a&l{NAME}"
      added lore:
        - "&a&lUNLOCKED"
  #
  log:
    slot: 0
    item: "oak_log"
    name: "Log Resource Node"
    tracks node: "log"
  cobblestone:
    slot: 1
    item: "cobblestone"
    name: "Cobblestone Resource Node"
    tracks node: "cobblestone"
  coal:
    slot: 2
    item: "coal_ore"
    name: "Coal Ore Resource Node"
    tracks node: "coal"
  iron:
    slot: 3
    item: "iron_ore"
    name: "Iron Ore Resource Node"
    tracks node: "iron"
  diamond:
    slot: 4
    item: "diamond_ore"
    name: "Diamond Ore Resource Node"
    tracks node: "diamond"
#
bots:
  # "radius" measured in blocks!
  # "inventory size" needs to be a multiple of 9!
  # "scan interval" measured in seconds!
  mining:
    radius:
      default:
        radius: 2
      level 2:
        cost: 8000000
        radius: 3
    inventory:
      default:
        title: "Auto Miner"
        size: 9
    scan interval:
      default:
        delay: 600
      level 2:
        cost: 200000
        delay: 540
      level 3:
        cost: 500000
        delay: 480
      level 4:
        cost: 1000000
        delay: 420
      level 5:
        cost: 2000000
        delay: 360
      level 6:
        cost: 2500000
        delay: 300
      level 7:
        cost: 5000000
        delay: 240
    blocks to mine:
      default:
        blocks: 1
      level 2:
        cost: 20000000
        blocks: 2
    #
    item: "armor_stand"
    name: "&6&lAuto Mining Bot (&r&7Right-Click&6&l)"
    lore:
      - "&7Place on an accessed"
      - "&7island to create an"
      - "&7auto resource node miner!"
      - " "
      - "&6&lRadius:&r &f{RADIUS} blocks"
      - "&6&lInventory Size:&r {INV_SIZE}"
      - "&6&lScan Interval:&r &f{SCAN_INTERVAL}"
      - "&6&lBlocks Per Interval:&r &f{BLOCKS_PER_INTERVAL}"
#
resources:
  pre lore:
    - "&7Resource"
  #
  items:
    - "coal"
#
science:
  gold:
    unrefined scrap:
      item: "glowstone_dust"
      name: "&eUnrefined Gold Scrap"
      lore:
        - "&7Ore Dust and rock that may contain"
        - "&7trace amounts of &egold&7."
        - " "
        - "&7Smelt in a Furnace for a"
        - "&7chance to find &eGold Scrap&7!"
        - " "
        - "&eGold &7can be used in /science!"
    ingot:
      item: "gold_ingot"
      name: "&eGold Ingot"
      lore:
        - "&7/science Resource"
        - " "
        - "&7Combine 9x together"
        - "&7to create a &eGold Block&7!"
#
cosmetic:
  pre lore:
    - " "
    - "&7&lCOSMETIC"
    - "&7This item cannot be used for crafting."
  #
#
cannot be insta broke:
  - "mob_spawner"
  - "ladder"
  - "dispenser"
  - "hopper"
  - "chest"
  - "trapped_chest"
  - "furnace"
#
drops:
  - "oak_log:resourcefragment:log"
  - "birch_log:resourcefragment:log"
  - "jungle_log:resourcefragment:log"
  - "dark_oak_log:resourcefragment:log"
  - "acacia_log:resourcefragment:log"
  - "cobblestone:resourcefragment:cobblestone"