# Made by RandomHashTags
messages:
  cannot place fragment:
    - "&c&l(!)&r &cYou cannot place this resource node fragment!"
  cannot place resource items:
    - "&c&l(!)&r &cYou cannot place Resource items!"
  #
  nodes:
    placed:
      - "&a&l(!)&r &a{TYPE} Resource Node placed on your island!"
      - "&7You can pickup this node by shift-breaking it!"
    placed notify:
      - "&a&l(!)&r &a{TYPE} Resource Node placed on your island!"
    destroyed:
      - "&c&l(!)&r &c{TYPE} has been destroyed!"
    respawn:
      - "&e&l(!)&r &e{TYPE} Resource Node will respawn in &n{TIME}!"
    pickup:
      - "&e&l(!)&r &eTo pickup a resource node block, you must be sneaking while breaking it."
    ready to be harvested:
      - "&e&l(!)&r &e{TYPE} Resource Node is ready to be harvested!"
    mined:
      - "&e&l(!)&r &e{TYPE} Resource Node mined: &7{PROGRESS} / {MAX} (&e{PROGRESS%}%&7)"
    #
    level too low to place node:
      - "&c&l(!)&r &cIsland Mining Level is too low to place {TYPE} Resource Node!"
      - "&7Requires /is Mining Level &l&n{REQUIRED_LEVEL}"
    skill advanced:
      - " "
      - " &6&l**&r &6Your Mining Skill has advanced to &lLevel {LEVEL}&r&6! &6&l**"
      - "&7Members can now placed {NODE} on the island!"
      - " "
#
skill:
  item: "diamond_pickaxe"
  name: "&a&lMining"
  type: "Mining"
#
gui:
  title: "/is mining"
  size: 18
  background:
    item: "black_stained_glass_pane"
    name: " "
  #
  settings:
    format:
      - " "
      - "&f{COMPLETION%}% &7Complete"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
      - "{OR}"
      - " "
      - "{RESPAWN_RATE}"
    or format:
      - " &7&l&nOR"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
    respawn rate:
      - "&f{RESPAWN%}% &7Respawn Rate"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Harvested"
    #
    locked:
      name: "&c&l{NAME}"
      added lore:
        - "&c&lLOCKED"
    unlocked:
      name: "&a&l{NAME}"
      added lore:
        - "&a&lUNLOCKED"
  #
  log:
    slot: 0
    item: "oak_log"
    name: "Log Resource Node"
    tracks node: "log"
  cobblestone:
    slot: 1
    item: "cobblestone"
    name: "Cobblestone Resource Node"
    tracks node: "cobblestone"
  coal:
    slot: 2
    item: "coal_ore"
    name: "Coal Ore Resource Node"
    tracks node: "coal"
  iron:
    slot: 3
    item: "iron_ore"
    name: "Iron Ore Resource Node"
    tracks node: "iron"
  diamond:
    slot: 4
    item: "diamond_ore"
    name: "Diamond Ore Resource Node"
    tracks node: "diamond"
#
bots:
  # "radius" measured in blocks!
  # "inventory size" needs to be a multiple of 9!
  # "scan interval" measured in seconds!
  mining:
    radius:
      default:
        radius: 2
      level 2:
        cost: 8000000
        radius: 3
    inventory:
      default:
        title: "Auto Miner"
        size: 9
    scan interval:
      default:
        delay: 600
      level 2:
        cost: 200000
        delay: 540
      level 3:
        cost: 500000
        delay: 480
      level 4:
        cost: 1000000
        delay: 420
      level 5:
        cost: 2000000
        delay: 360
      level 6:
        cost: 2500000
        delay: 300
      level 7:
        cost: 5000000
        delay: 240
    blocks to mine:
      default:
        blocks: 1
      level 2:
        cost: 20000000
        blocks: 2
    #
    item: "armor_stand"
    name: "&6&lAuto Mining Bot (&r&7Right-Click&6&l)"
    lore:
      - "&7Place on an accessed"
      - "&7island to create an"
      - "&7auto resource node miner!"
      - " "
      - "&6&lRadius:&r &f{RADIUS} blocks"
      - "&6&lInventory Size:&r {INV_SIZE}"
      - "&6&lScan Interval:&r &f{SCAN_INTERVAL}"
      - "&6&lBlocks Per Interval:&r &f{BLOCKS_PER_INTERVAL}"
#
resources:
  pre lore:
    - "&7Resource"
  #
  items:
    - "coal"
#
resource item:
  pre lore:
    - " "
    - "&7&lRESOURCE ITEM"
    - "&7This item can be used for crafting."
  #
  oak planks:
    item: "oak_planks"
  stick:
    item: "stick"
  cobblestone:
    item: "cobblestone"
    lore:
      - "&7You can craft Chainmail Armor with this."
  iron ingot:
    item: "iron_ingot"
  diamond:
    item: "diamond"
#
resource fragments:
  log:
    item: "dead_bush"
    name: "&fLog Resource Fragment"
    lore:
      - " "
      - "&8&lRecipe"
      - " &f&l*&r &f5x = Log Node"
      - " "
      - "&7Can be created into Resource Nodes."
  cobblestone:
    item: "light_gray_dye"
    name: "&fCobblestone Resource Fragment"
    lore:
      - " "
      - "&8&lRecipe"
      - " &f&l*&r &f64x = Cobblestone Node"
      - " "
      - "&7Can be created into Resource Nodes."
  #
  mob_spawner:
    item: "prismarine_shard"
    name: "&f&lSpawner Shard (&r&7{TYPE}&f&l)"
    lore:
      - "&7Combine with &l&n9&r &f&lSpawner Shards"
      - "&f&l(&r&7{TYPE}&f&l)&r &7to create a new"
      - "&f&lMob Spawner (&r&7{TYPE}&f&l)&r&7!"
#
scraps:
  pre lore:
    - "&7Resource"
  #
  oak:
    item: "oak_button"
    name: "&fWood Scrap"
  stone:
    item: "stone_button"
    name: "&fStone Scrap"
  iron:
    item: "light_gray_dye"
    name: "&8Iron Scrap"
  gold:
    item: "yellow_dye"
    name: "&eGold Scrap"
  diamond:
    item: "light_blue_dye"
    name: "&bDiamond Scrap"
#
science:
  gold:
    fragment:
      item: "gold_nugget"
      name: "&eGold Ore Resource Fragment"
      lore:
        - " "
        - "&8&lRecipe"
        - " &e&l*&r &e32x = Gold Ore Node"
        - " "
        - "&7Can be created into Resource Nodes."
    unrefined scrap:
      item: "glowstone_dust"
      name: "&eUnrefined Gold Scrap"
      lore:
        - "&7Ore Dust and rock that may contain"
        - "&7trace amounts of &egold&7."
        - " "
        - "&7Smelt in a Furnace for a"
        - "&7chance to find &eGold Scrap&7!"
        - " "
        - "&eGold &7can be used in /science!"
    scrap:
      item: "yellow_dye"
      name: "&eGold Scrap"
      lore:
        - "&7/science Resource"
        - " "
        - "&7Combine 64x together"
        - "&7to created a &eGold Ingot&7!"
    ingot:
      item: "gold_ingot"
      name: "&eGold Ingot"
      lore:
        - "&7/science Resource"
        - " "
        - "&7Combine 9x together"
        - "&7to create a &eGold Block&7!"
#
nodes:
  default: "log"
  types:
    DEFAULT:
      lore:
        - "&7Resource Node"
        - " "
        - "&f&lLoot"
        - "{LOOT}"
        - " "
        - "&f&lRespawn Time"
        - " &f{RESPAWN}"
        - " "
        - "&7Place this resource node on your island!"
    RARE:
      lore:
        - "&7Resource Node"
        - " "
        - "&8&lLoot"
        - "{LOOT}"
        - " "
        - "&8&lRespawn Time"
        - " &8{RESPAWN}"
        - " "
        - "&7Place this resource node on your island!"
    GOLD:
      lore:
        - "&7Resource Node"
        - " "
        - "&e&lLoot"
        - "{LOOT}"
        - " "
        - "&e&lRespawn Time"
        - " &e{RESPAWN}"
        - " "
        - "&7Place this resource node on your island!"
    DIAMOND:
      lore:
        - "&7Resource Node"
        - " "
        - "&b&lLoot"
        - "{LOOT}"
        - " "
        - "&b&lRespawn Time"
        - " &b{RESPAWN}"
        - " "
        - "&7Place this resource node on your island!"
  # "respawn time" is the default respawn time, and is measured in seconds!
  log:
    type: DEFAULT
    respawn time: 60
    value: 500
    harvest block: OAK_LOG
    node block: OAK_PLANKS
    node name: "Log"
    node {TYPE}: "Log Nodes"
    item: "oak_log"
    name: "&fLog Node"
    loot:
      - "scrap:oak; &f&l*&r &f1x Wood Scrap"
  cobblestone:
    type: DEFAULT
    required island level: 4
    respawn time: 120
    value: 1000
    harvest block: COBBLESTONE
    node block: STONE
    node name: "Cobblestone"
    node {TYPE}: "Stone"
    required node: "log"
    completion: 50
    item: "cobblestone"
    name: "&fCobblestone Node"
    loot:
      - "scrap:stone; &f&l*&r &f1x Stone Scrap"
  coal:
    type: DEFAULT
    required island level: 8
    respawn time: 240
    value: 5000
    harvest block: COAL_ORE
    node block: STONE
    node name: "Coal"
    node {TYPE}: "Coal Nodes"
    required node: "cobblestone"
    completion: 250
    item: "coal_ore"
    name: "&fCoal Ore Node"
    loot:
      - "resource:coal; &f&l*&r &f1x Coal"
  iron:
    type: RARE
    respawn time: 300
    value: 25000
    harvest block: IRON_ORE
    node block: IRON_BLOCK
    node name: "Iron"
    node {TYPE}: "Iron Nodes"
    required node: "coal||cobblestone"
    completion: 1000
    item: "iron_ore"
    name: "&8Iron Ore Node"
    loot:
      - "scrap:iron; &8&l*&r &81x Iron Scrap"
  gold:
    type: GOLD
    respawn time: 60
    value: 0
    harvest block: GOLD_ORE
    node block: GOLD_BLOCK
    node name: "Gold"
    node {TYPE}: "Gold Nodes"
    required node: "stone"
    completion: 1000
    item: "gold_ore"
    name: "&eGold Ore Node"
    loot:
      - "scrap:gold; &e&l*&r &e1x Gold Scrap"
  diamond:
    type: DIAMOND
    respawn time: 900
    value: 125000
    harvest block: DIAMOND_ORE
    node block: IRON_BLOCK
    node name: "Diamond"
    node {TYPE}: "Diamond Nodes"
    required node: "iron"
    completion: 2500
    item: "diamond_ore"
    name: "&bDiamond Ore Node"
    loot:
      - "scrap:diamond; &b&l*&r &b1x Diamond Scrap"
#
unrefined:
  iron block:
    item: "iron_block"
    name: "&8Unrefined Iron Block"
    lore:
      - "&7Smelt in a furnace to refine"
      - "&7into a &8Refined Iron Block."
  diamond block:
    item: "diamond_block"
    name: "&bUnrefined Diamond Block"
    lore:
      - "&7Smelt in a furnace to refine"
      - "&7into a &bRefined Diamond Block."
#
refined:
  iron block:
    item: "iron_block"
    name: "&8Refined Iron Block"
    lore:
      - "&7Combine &816x &7together"
      - "&7to craft a &8Iron ore Resource Node."
  diamond block:
    item: "diamond_block"
    name: "&bRefined Diamond Block"
    lore:
      - "&7Combine &b16x &7together"
      - "&7to craft a &bDiamond ore Resource Node."
#
cosmetic:
  pre lore:
    - " "
    - "&7&lCOSMETIC"
    - "&7This item cannot be used for crafting."
  #
#
cannot be insta broke:
  - "mob_spawner"
  - "ladder"
  - "dispenser"
  - "hopper"
  - "chest"
  - "trapped_chest"
  - "furnace"
#
drops:
  - "oak_log:resourcefragment:log"
  - "birch_log:resourcefragment:log"
  - "jungle_log:resourcefragment:log"
  - "dark_oak_log:resourcefragment:log"
  - "acacia_log:resourcefragment:log"
  - "cobblestone:resourcefragment:cobblestone"