# Made by RandomHashTags
messages:
  help:
    - "&b&lRandom Skyblock Commands"
    - "&b/is create"
    - " &fCreate a personal Skyblock island."
    - "&b/is home"
    - " &fTeleport to your own island."
    - "&b/is tp [player]"
    - " &fVisit a friend's Island!"
    - "&b/is members"
    - " &fEdit your existing island members."
    - "&b/is add [player]"
    - " &fGive the specified player member access."
    - "&b/is remove [player]"
    - " &fRemoves island access from the specified member."
    - "&b/is ban [player]"
    - " &fPermanently banish a player from your island."
    - "&b/is kick [player]"
    - " &fKick a player from your island back to spawn."
    - "&b/is delete"
    - " &fDelete your island!"
    - "&b/is open/close [description]"
    - " &fOpen or close your home location to the public!"
    - "&b/is list"
    - " &fOpen the public island list!"
    - "&b/is setwarp/delwarp"
    - " &fSet or remove a public island warp!"
    - " "
  zero arguments:
    - "&b&lRandom Skyblock"
    - " &fRun &b/is create &fto start your island!"
  #
  create:
    - " "
    - "&e&l(!)&r &eWelcome to your new /island!"
    - "&7To access your island management menu, use the &f/is &7command."
    - "&7To get some starter items, use &f/kit starter"
    - "&7Need help getting started? Check out your &f/is challenges&7!"
    - " "
    - " "
  insta break tutorial:
    - "&e&l(!)&r &eInstabreak is enabled on your island! This feature can be disabled in &n/toggles&r&e."
  fallen into the void:
    - " "
    - "&e&l(!)&r &eYou have fallen into the Void!"
    - "&7You have been safely returned to spawn!"
    - " "
  home doesnt have island:
    - "&c&l(!)&r &cThis account has no island, create one with '/is create'!"
  already have an island:
    - "&c&l(!)&r &cYou already have an island!"
    - "&7Use '/is home' to travel to it!"
  delete:
    - "&c&l(!)&r &cYour island has been deleted!"
  delete must wait:
    - "&c&l(!)&r &cYou must wait {TIME} before you can delete your island again!"
  need island:
    - "&c&l(!)&r &cYou don't have an island!"
    - "&7Use '/is create' to create one!"
  sethome:
    - "&a&l(!)&r &a/is home location set to {X}&lx&r&a, {Y}&ly&r, &a{Z}&lz&r&a!"
  #
  setwarp:
    - "&e&l(!)&r &eIsland warp set to your island!"
    - "&7Players can now '/is warp {PLAYER}' to travel here!"
  delwarp:
    - "&e&l(!)&r &eYour island warp has been deleted!"
  delwarp no warp:
    - "&c&l(!)&r &cYou do not have a warp set to delete!"
  your island is not open to the public:
    - "&c&l(!)&r &cYour island is not open to the public!"
  no island found to warp to:
    - "&c&l(!)&r &cNo island found to warp to!"
  island open to public:
    - "&a&l(!)&r &aYour island is now open to the public!"
  island already open to public:
    - "&c&l(!)&r &cIsland is already open to the public!"
  no longer open to public:
    - "&e&l(!)&r &eYour Island is no longer open to the public."
  warp already on island:
    - "&c&l(!)&r &cYou are already on this island!"
  #
  already created origin:
    - "&c&l(!)&r &cYou have already created an island!"
    - "&7If you wish to change your origin, you must delete your island with '/is delete'."
  need to upgrade island radius to place block there:
    - "&c&l(!)&r &cYou cannot build outside your Skyblock region in the Skyblock world!"
  cannot pickup items on island:
    - "&c&l(!)&r &cYou cannot pickup items on {IS_CREATOR}'s Island!"
  cannot build or break on island:
    - "&c&l(!)&r &cYou must be a member of {IS_CREATOR}'s Skyblock to build on their island!"
  cannot build outside of your region:
    - "&c&l(!)&r &cYou cannot build outside of your Skyblock region in the Skyblock world!"
  cannot interact with entities on island:
    - "&c&l(!)&r &cYou cannot interact with entities on {PLAYER}'s Island!"
  cannot damage mobs on island:
    - "&c&l(!)&r &cYou cannot damage mobs on {PLAYER}'s Island!"
  #
  kick usage:
    - "&cUsage: &7/is kick <player>"
  kicked:
    - "&a&l(!)&r &aKicking &l{TARGET}&r &afrom your island!"
  kicked notify:
    - "&a&l(!)&r &a{PLAYER} kicked {TARGET} from your island!"
  been kicked:
    - "&c&l(!)&r &cYou've been kicked from {IS_CREATOR}'s island by {PLAYER}!"
  kick not on island:
    - "&c&l(!)&r &c{TARGET} is not currently on your island!"
  cannot kick self:
    - "&c&l(!)&r &cYou cannot kick yourself!"
  add:
    - "&a&l(!)&r &a{PLAYER} is now a member of your island!"
  #
  warp usage:
    - "&cUsage: &7/is warp <memberName>"
  warp to island:
    - "&e&l(!)&r &eVisiting {PLAYER}'s Island..."
    - " "
  unable to warp to island:
    - "&c&l(!)&r &cUnable to find online player {INPUT}!"
  no island to warp to:
    - "&c&l(!)&r &cNo island found to warp to!"
  try warp self:
    - "&c&l(!)&r &cUse '/is home' to warp to your island!"
  #
  remove usage:
    - "&cUsage: &7/is remove [player]"
  remove not member:
    - "&c&l(!)&r &c{PLAYER} is not a member of your island!"
  edit rank:
    - "&a7l(!)&r &a{PLAYER} is now '{RANK}&r&a'!"
  invite usage:
    - "&cUsage: &7/is invite [player]"
  invite pending:
    - "&c&l(!)&r &c{PLAYER} already has a pending island invite!"
  invite already member:
    - "&c&l(!)&r &c{PLAYER} is already a member of your island!"
    - "&7Use /is members to edit your island members!"
  invite sent:
    - "&a&l(!)&r {PLAYER} &ahas been invited to {IS_CREATOR}'s Island!"
  invite receive:
    - "&e&l(!)&r &f{PLAYER} &ehas invited you to &n{IS_CREATOR}&r&e's island!"
    - "&7Use '/is join {IS_CREATOR}' to accept their invite!"
  invite accept:
    - "&a&l(!)&r &a{PLAYER} has accepted {SENDER}'s Invite to {IS_CREATOR}'s island!"
  invite expired:
    - "&c&l(!)&r &cYour invite to {PLAYER} has expired!"
  cannot invite self:
    - "&c&l(!)&r &cYou cannot add yourself!"
  no invite to join:
    - "&c&l(!)&r &cNo island invite found from {PLAYER}!"
  join usage:
    - "&cUsage: &7/is join <player>"
  #
  ban:
    - "&c&l(!)&r &c{PLAYER} has banned {TARGET} from {IS_CREATOR}'s island!"
  ban usage:
    - "&cUsage: &7/is ban <player>"
  cannot ban self:
    - "&c&l(!)&r &cYou cannot ban yourself!"
  already banned:
    - "&c&l(!)&r &c{TARGET} is already banned from your island!"
  unban:
    - "&c&l(!)&r &c{PLAYER} has unbanned {TARGET} from {IS_CREATOR}'s island!"
  unban usage:
    - "&cUsage: &7/is unban <player>"
  not banned:
    - "&c&l(!)&r &c{TARGET} is not banned from your island!"
  #
  placed spawner:
    - "&e&lYou can break this mob spawner at anytime with your fists to get the block back, no Silk Touch required!"
  placed rabbit spawner:
    - "&e&lHINT:&r &eRabbits need GRASS blocks to spawn, be sure to place some grass around your spawner!"
  #
  taken control of island top:
    - "&e&l(!)&r &e{TAG} has taken control of /is top &l#1&r &ewith &l$&r &e{TOTAL_MEMBER_BAL} combines member balances!"
#
island:
  world: "island_world"
  deletion delay: 3600 # Measured in seconds
  distance between islands: 256 # Measured in blocks. 8 blocks = 1 chunk. Default is 256 blocks (32 chunks)
  #
  allowed damage:
    fall: false
    lava: false
    fire: false
    magma block: fase
    drowning: false
    pvp: false
  #
#
#
roles:
  default for member: MEMBER
  default for owner: OWNER
  click to assign:
    - "&7Left-Click to assign this rank."
  #
  viewing members:
    - " "
    - "&b&lIsland Rank"
    - "{RANK}"
#
delete:
  title: "Confirm Island Deletion"
  size: 9
  confirm:
    item: "lime_stained_glass_pane"
    name: "&a&lConfirm"
    lore:
      - "&7Click to confirm island deletion!"
      - " "
      - "&c&lNOTE:&r &cThis can &nNOT&r &cbe undone!"
  cancel:
    item: "red_stained_glass_pane"
    name: "&c&lCancel Deletion"
    lore:
      - "&7Click to cancel this action."
  #
  one:
    slot: 0
    item: "confirm"
  two:
    slot: 1
    item: "confirm"
  three:
    slot: 2
    item: "confirm"
  four:
    slot: 3
    item: "confirm"
  five:
    slot: 4
    item: "black_stained_glass_pane"
    name: " "
  six:
    slot: 5
    item: "cancel"
  seven:
    slot: 6
    item: "cancel"
  eight:
    slot: 7
    item: "cancel"
  nine:
    slot: 8
    item: "cancel"
#
name:
  length: 3:16
  case sensitive: false
  blacklisted:
    - "`"
    - "~"
    - "!"
    - "@"
    - "#"
    - "$"
    - "%"
    - "^"
    - "&"
    - "*"
    - "("
    - ")"
    - "-"
    - "_"
    - "="
    - "+"
    - "["
    - "{"
    - "]"
    - "}"
    - "\\"
    - "|"
    - ";"
    - ":"
    - "'"
    - "\""
    - ","
    - "<"
    - "."
    - ">"
    - "/"
    - "?"
#
origins:
  selected:
    - " "
    - "&a&l* YOUR ORIGIN *"
  gui:
    title: "Island Origins"
    size: 9
    background:
      item: "black_stained_glass_pane"
      name: " "
#
gui:
  title: "Island ({PLAYER})"
  type: DISPENSER
  size: 9
  # Available types: MANAGE, CHALLENGES, LEVELS, TP_HOME, INFO, SKILLS
  management:
    slot: 1
    type: MANAGE
    item: "player_head_item"
    owner: "{PLAYER}"
    name: "&b&lIsland Management"
    lore:
      - "&7Click to view and manage"
      - "&7all island members and their ranks."
      - " "
      - "&b&l{MEMBERS} Member(s)"
  challenges:
    slot: 3
    type: CHALLENGES
    item: "enchanted_book"
    name: "&b&lIsland Challenges"
    lore:
      - "&7Click to view island challenges!"
  levels:
    slot: 4
    type: LEVELS
    item: "experience_bottle"
    name: "&b&lIsland Levels"
    lore:
      - "&7Click to view your current"
      - "&7island level, and view rewards!"
  home:
    slot: 5
    type: TP_HOME
    item: "eye_of_ender"
    name: "&b&lTravel Home"
    lore:
      - "&bTo Set Home Location:"
      - "&7Use /is sethome!"
      - " "
      - "&7Click to travel to your island!"
  info:
    slot: 6
    type: INFO
    item: "book_and_quill"
    name: "&b&lIsland Info"
    lore:
      - "&7Every island level will grant you"
      - "&7additional benefits to your island."
      - " "
      - "&a&lIsland Level"
      - " &f{LEVEL}"
      - " "
      - "&b&lOrigin"
      - " {ORIGIN}"
      - " "
      - "&e&lIsland Radius"
      - " &f{RADIUS}"
      - " "
      - "&6&lIsland Value"
      - " &6Spawners: &f&l$&r&f{SPAWNER_VALUE}"
      - " &6Resource Nodes: &f&l$&r&f{RESOURCE_NODE_VALUE}"
      - " &6Island Levels: &f&l$&r&f{ISLAND_VALUE}"
      - " "
      - "&7Click to view island levels."
  skills:
    slot: 7
    type: SKILLS
    item: "emerald"
    name: "&b&lIsland Skills"
    lore:
      - "&7Unlock new island skill levels"
      - "&7to gain access to better items!"
      - " "
      - "&b&lSkill Levels"
      - " &b&l*&r &fFarming: &b{FARMING_LEVEL}"
      - " &b&l*&r &fSlayer: &b{SLAYER_LEVEL}"
      - " &b&l*&r &fMining: &b{MINING_LEVEL}"
      - " "
      - "&7Click to view your island skills!"
  commands:
    slot: 8
    item: "book"
    name: "&b&lIsland Commands"
    lore:
      - "&b&lServer Skyblock Commands"
      - "&b/is create"
      - " &fCreate a personal Skyblock island."
      - "&b/is home"
      - " &fTeleport to your own island."
      - "&b/is tp [player]"
      - " &fVisit a friends Island!"
      - "&b/is members"
      - " &fEdit your existing island members."
      - "&b/is add [player]"
      - " &fGive the specified player member access."
      - "&b/is remove [player]"
      - " &fRemoves island access from the specified member."
      - "&b/is ban [player]"
      - " &fPermanently banish a player from your island."
      - "&b/is kick [player]"
      - " &fKick a player from your island back to spawn."
      - "&b/is delete"
      - " &fDelete your island!"
      - "&b/is open/close [description]"
      - " &fOpen or close your home location to the public!"
      - "&b/is warplist"
      - " &fOpen the public island list!"
#
members:
  title: "Island Members"
  back:
    item: "barrier"
    name: "&c&lPrevious Menu"
    lore:
      - "&7Click to return to the main menu!"
#
skills:
  title: "Island Skills"
  size: 9
  background:
    item: "black_stained_glass_pane"
    name: " "
  #
#
open islands:
  gui:
    title: "Open Islands"
    size: 54
    #
#