# Made by RandomHashTags
messages:
  plant grown:
    - "&e&l(!)&r &e{TYPE} grown: &7{PROGRESS} / {MAX} &e(&e{PROGRESS%}%&7)"
  plant grown sent when countdown ends in: "0;5"
  skill advanced:
    - " "
    - " &6&l**&r &6Your Farming Skill has advanced to &lLevel {LEVEL}&r&6! &6&l**"
    - "        &7Members can now plant &n{TYPE}&r &7on the island!"
    - " "
  unlocked recipe:
    - "&a&l(!)&r &a{PLAYER} has unlocked the {TYPE} Recipe &afor {IS_CREATOR}'s Island!"
  has not discovered recipe:
    - "&c&l(!)&r &cYour Island has not discovered the recipe to plant {TYPE}!"
    - "&7Farming Recipes can be found inside the /adventures!"
#
default recipes:
  - WHEAT
  - POTATOES
#
skill:
  slot: 0
  item: "wheat"
  name: "&a&lFarming"
  lore:
    - " "
    - "&b&lLevel"
    - " &f{LEVEL}"
    - " "
    - "&7Click to view Island Farming levels!"
#
info:
  title: "Farming Info ({PLAYER})"
  size: 9
  #
  settings:
    format:
      - " "
      - "&f{COMPLETION%}% &7Complete"
      - "&7{PROGRESS} / {COMPLETION} {TYPE} Grown"
      - "{FARMING_RECIPE}"
      - " "
      - "{STATUS}"
    needs recipe: "&c&l✗"
    has recipe: "&a&l✓"
    completed:
      prefix: "&a&l"
      status:
        - "&a&lCOMPLETED"
    locked:
      prefix: "&c&l"
      status:
        - "&c&lLOCKED"
    in progress:
      prefix: "&e&l"
      status:
        - "&e&lIN PROGRESS"
    farming recipe:
      - "&7[{HAS_RECIPE}&r&7]&r &7Farming Recipe: {RECIPE_NAME}"
    #
    wheat:
      slot: 0
      required recipe: "wheat"
      item: "wheat_seeds"
      name: "&a&lWheat"
      lore:
        - " "
        - "&7You're a natural farmer!"
    potatoes:
      slot: 1
      required skill: "wheat"
      required recipe: "potatoes"
      item: "potato"
      name: "Potatoes"
    carrots:
      slot: 2
      required skill: "potatoes"
      required recipe: "carrots"
      item: "carrot_item"
      name: "Carrots"
    sugar cane:
      slot: 3
      required skill: "carrots"
      required recipe: "sugar cane"
      item: "sugar_cane"
      name: "Sugar Cane"
    beetroots:
      slot: 4
      required skill: "sugar cane"
      required recipe: "beetroots"
      item: "beetroot_seeds"
      name: "Beetroot"
    nether warts:
      slot: 5
      required skill: "beetroots"
      required recipe: "nether warts"
      item: "nether_wart"
      name: "Nether Warts"
    melons:
      slot: 6
      required skill: "nether warts"
      required recipe: "melons"
      item: "melon_slice"
      name: "Melons"
    pumpkins:
      slot: 7
      required skill: "melons"
      required recipe: "pumpkins"
      item: "pumpkin"
      name: "Pumpkins"
    chorus fruit:
      slot: 8
      required skill: "pumpkins"
      required recipe: "chorus fruit"
      item: "chorus_plant"
      name: "Chorus Fruit"
#